#!/bin/bash

#./rload r.log 00:00:00 23:59:59 $@
#./rload r.log 11:00:00 12:00:00 $@
#./rload r.log 00:00:00 23:59:59 -q doxie.HeaderFileRollupService -n 10

export TZ=EDT4

./logstats -l r.log -s 10:31:40 -e 10:31:48 $@

